Code.require_file("app/spec/espec_phoenix_extend.ex")
Code.require_file("app/web/web.ex")
Code.require_file("app/web/router.ex")
Code.require_file("app/web/models/post.ex")
Code.require_file("app/web/controllers/posts_controller.ex")
Code.require_file("app/web/views/posts_view.ex")
