Code.require_file("spec/app/web/web.ex")
Code.require_file("spec/app/web/router.ex")
Code.require_file("spec/app/web/models/post.ex")
Code.require_file("spec/app/web/controllers/posts_controller.ex")
Code.require_file("spec/app/web/views/posts_view.ex")
