language: elixir
elixir:
- 1.5.3
- 1.6.6
- 1.7.0
- 1.7.2
otp_release:
- 19.2
- 20.0
- 21.0
matrix:
  exclude:
  - elixir: 1.5.3
    otp_release: 21.0
  - elixir: 1.6.0
    otp_release: 21.0
sudo: false
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd rumbrella/apps/rumbl
  - cat config/database.config >> config/test.exs
  - cat config/test.secret.exs >> config/dev.secret.exs
  - cd ../../..
script:
  - mix deps.get
  - mix espec
  - cd rumbrella
  - mix deps.get
  - mix test
  - mix espec
notifications:
  recipients:
    - anton.mishchuk@gmail.com
